name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
    
  pull_request:
    branches: [master, main]


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: .*static/.*
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install form requirements.txt
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
          
      - name: Run application
        uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
      - run: python app.py
